version: "3.8"

volumes:
  rabbitmq_data:

services:

 
  #######################################################
  # Agent: The Agent microservice
  #######################################################
  agent:
    build:
      context: ./
      dockerfile: agent.Dockerfile
    image: faithanggg/agent:esd
    restart: always
    environment:
      dbURL: mysql2://is213@host.docker.internal:3306/property_management
      PYTHONUNBUFFERED: 1
    ports:
      - "5003:5003"

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
      
  #################################################
  # Auction: The Auction microservice
  #################################################
  auction:
    build:
      context: ./
      dockerfile: auctionService.Dockerfile
    image: faithanggg/auctionservice:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/property_management
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"

  ###################################
  # Error: The Error microservice
  ###################################
  error:
    build:
      context: ./
      dockerfile: error.Dockerfile
    image: faithanggg/error:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ##################################
  # Bids: The Bids microservice
  ##################################
  bids:
    build:
      context: ./
      dockerfile: bids.Dockerfile
    image: faithanggg/bids:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/property_management
      PYTHONUNBUFFERED: 1
    ports:
      - "5500:5500"


  ##################################
  # Booking: The Booking microservice
  ##################################
  booking:
    build:
      context: ./
      dockerfile: booking.Dockerfile
    image: faithanggg/booking:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/property_management
      PYTHONUNBUFFERED: 1
      GOOGLE_APPLICATION_CREDENTIALS: ./credentials.json 
      client_id: 976196717049-ln65umr1112o4mrd9533rbon20qf4iir.apps.googleusercontent.com 
      client_secret: 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 
      refresh_token: 1//0gArI7UZjvbC-CgYIARAAGBASNwF-L9Ir2ApBBtXLQq6MRFp1xG55jkjohbGZgJvNXG3fL8hAGN0xE764KJ0mTd1nxYj_dbt46jw
      token: ya29.a0Ael9sCOgFOKrFj1gJaQsjQGvRyQhG4rqz0Jwgwz8DvdCR2GFCqeaeOYHbM1W4SD7c7Xh0YQbwIVkYwAqXmmCb7G3waHyFWJ_pPHyT4MQ9ecHdHh5ypj8Ew95Z6EB0FCTMm3qEaabFNJNBEAKdTUUQ2NF9QjKHhNEaCgYKAUgSARASFQF4udJh7TZAQ_ECA5l5LcICeUUygg0167
      project_id: groovy-height-381506
    ports:
      - "5005:5005"


  ##################################
  # Customer: The Customer microservice
  ##################################
  customer:
    build:
      context: ./
      dockerfile: customer.Dockerfile
    image: faithanggg/customer:esd
    restart: always
    environment:
      dbURL: mysql2://is213@host.docker.internal:3306/property_management
      PYTHONUNBUFFERED: 1
    ports:
      - "5700:5700"


  ##################################
  # Notification: The Notications microservice
  ##################################
  notification:
    build:
      context: ./
      dockerfile: notification.Dockerfile
    image: faithanggg/notification:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      EMAIL_PASSWORD: vgcpmtfhuchlyizw

  ##################################  
  # Property: The Property microservice
  ##################################
  property:
    build:
      context: ./
      dockerfile: property.Dockerfile
    image: faithanggg/property:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/property_management
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"


  ############################################### 
  # Accept Booking: The Accept Booking microservice
  ###############################################
  accept_booking:
    build:
      context: ./
      dockerfile: accept_booking.Dockerfile
    image: faithanggg/accept_booking:esd
    restart: always
    depends_on:
      - booking
      - customer
      - notification
      - error
      - rabbitmq
      - property
      - agent
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      booking_URL: http://booking:5005/booking
      customer_URL: http://customer:5700/customer
      property_URL: http://property:5001/property
      agent_URL: http://agent:5003/agent
      PYTHONUNBUFFERED: 1
    ports:
      - "5101:5101"

  ###############################################
  # Add Listing: The Add Listing microservice
  ###############################################
  add_listing:
    build:
      context: ./
      dockerfile: add_listing.Dockerfile
    image: faithanggg/add_listing:esd
    restart: always
    depends_on:
      - property
      - customer
      - notification
      - auction
      - agent
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      auction_URL: http://auction:5002/auctions
      customer_URL: http://customer:5700/customer
      property_URL: http://property:5001/property
      agent_URL: http://agent:5003/agent
      PYTHONUNBUFFERED: 1
    ports:
      - "5200:5200"

  ###############################################
  # Close Bid: The Close Bid microservice
  ###############################################
  close_bids:
    build:
      context: ./
      dockerfile: closebid.Dockerfile
    image: faithanggg/close_bids:esd
    restart: always
    depends_on:
      - auction
      - customer
      - notification
      - property
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      auction_URL: http://auction:5002/auctions
      customer_URL: http://customer:5700/customer
      property_URL: http://property:5001/property
      PYTHONUNBUFFERED: 1
    ports:
      - "5801:5801"

  ###############################################
  # Make Bid: The Make Bid microservice
  ###############################################
  make_bids:
    build:
      context: ./
      dockerfile: make_bid.Dockerfile
    image: faithanggg/make_bid:esd
    restart: always
    depends_on:
      - auction
      - customer
      - notification
      - property
      - bids
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      auction_URL: http://auction:5002/auctions
      customer_URL: http://customer:5700/customer
      property_URL: http://property:5001/property
      bid_URL: http://bids:5500/bids
      PYTHONUNBUFFERED: 1
    ports:
      - "5900:5900"


  ###############################################
  # Make Booking: The Make Booking microservice
  ###############################################
  make_booking:
    build:
      context: ./
      dockerfile: makebooking.Dockerfile
    image: faithanggg/make_booking:esd
    restart: always
    depends_on:
      - booking
      - notification
      - property
      - agent
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      booking_URL: http://booking:5005/booking
      property_URL: http://property:5001/property
      agent_URL: http://agent:5003/agent
      PYTHONUNBUFFERED: 1
    ports:
      - "5800:5800"

  ###############################################
  # Search: The Search microservice
  ###############################################
  search:
    build:
      context: ./
      dockerfile: search.Dockerfile
    image: faithanggg/search:esd
    restart: always
    depends_on:
      - property
      - agent
      - notification
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      property_URL: http://property:5001/property
      agent_URL: http://agent:5003/agent
      PYTHONUNBUFFERED: 1
    ports:
      - "5106:5106"

  ################################################
  # Get Bids: The Get Bids microservice
  ###############################################
  get_bids:
    build:
      context: ./
      dockerfile: get_bids.Dockerfile
    image: faithanggg/get_bids:esd
    restart: always
    depends_on:
      - notification
      - property
      - bids
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      property_URL: http://property:5001/property
      bid_URL: http://bids:5500/bids
      PYTHONUNBUFFERED: 1
    ports:
      - "5029:5029"


  ##############################################
  # Get Booking: The Get Booking microservice
  ###############################################
  get_booking:
    build:
      context: ./
      dockerfile: get_booking.Dockerfile
    image: faithanggg/get_booking:esd
    restart: always
    depends_on:
      - notification
      - property
      - customer
      - booking
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      property_URL: http://property:5001/property
      booking_URL: http://booking:5005/booking
      customer_URL: http://customer:5700/customer
      PYTHONUNBUFFERED: 1
    ports:
      - "5102:5102"

  ###############################################################
  # Get Property Details: The Get Property Details microservice
  ###############################################################
  get_property_details:
    build:
      context: ./
      dockerfile: get_property_details.Dockerfile
    image: faithanggg/get_property_details:esd
    restart: always
    depends_on:
      - notification
      - property
      - agent
      - bids
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      property_URL: http://property:5001/property
      bid_URL: http://bids:5500/bids
      agent_URL: http://agent:5003/agent
      PYTHONUNBUFFERED: 1
    ports:
      - "5009:5009"

  ###############################################
  # Profile Page: The Profile Page microservice
  ###############################################
  profile_page:
    build:
      context: ./
      dockerfile: profile_page.Dockerfile
    image: faithanggg/profile_page:esd
    restart: always
    depends_on:
      - customer
      - notification
      - agent
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      customer_URL: http://customer:5700/customer
      agent_URL: http://agent:5003/agent
      PYTHONUNBUFFERED: 1
    ports:
      - "5123:5123"

  ###############################################
  # Login: The Login microservice
  ###############################################
  login:
    build:
      context: ./
      dockerfile: login.Dockerfile
    image: faithanggg/login:esd
    restart: always
    depends_on:
      - customer
      - notification
      - agent
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      customer_URL: http://customer:5700/customer
      agent_URL: http://agent:5003/agent
      PYTHONUNBUFFERED: 1
    ports:
      - "5805:5805"
